version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:25.4
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_DB=ch
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native TCP protocol
      - "9009:9009"  # Interserver communication
    volumes:
      - ${HOME}/docker/clickhouse/25.4/data:/var/lib/clickhouse
      - ${HOME}/docker/clickhouse/25.4/logs:/var/log/clickhouse-server
    restart: unless-stopped
